# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d22e63b4b5b120bbd15893968ed396baf1b111ae7d0b853aecc45488179185d87c69f829f5281528421f229f61ba6cf13d43b068d449ac4a30efc91de92f0f9c

test:
  secret_key_base: 7c41040aa3911f1854fea8a32cace1b5cf64c7677bb174dcb634c57029de83da29e58503e5bb7ab97bd17a9c8cd2eaccee2bdc285517907cf8eede961bf23026

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
